name: gex2adt_v2
channels:
  - pytorch
  - anaconda
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _r-mutex=1.0.1
  - absl-py=1.4.0
  - aiohttp=3.8.3
  - aiosignal=1.3.1
  - alsa-lib=1.2.8
  - anndata=0.8.0
  - anyio=3.5.0
  - argon2-cffi=20.1.0
  - asttokens=2.0.5
  - async-timeout=4.0.2
  - attr=2.5.1
  - attrs=21.4.0
  - babel=2.9.1
  - backcall=0.2.0
  - beautifulsoup4=4.11.1
  - binutils_impl_linux-64=2.39
  - blas=1.0
  - bleach=4.1.0
  - blinker=1.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bwidget=1.9.14
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2023.5.7
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cachetools=5.3.0
  - cairo=1.16.0
  - certifi=2023.5.7
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - chex=0.1.5
  - click=8.1.3
  - colorama=0.4.6
  - commonmark=0.9.1
  - contextlib2=21.6.0
  - contourpy=1.0.6
  - cryptography=37.0.1
  - cudatoolkit=11.6.0
  - cudnn=8.4.1.50
  - curl=7.88.1
  - cycler=0.11.0
  - dataclasses=0.8
  - dbus=1.13.18
  - debugpy=1.5.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - dm-tree=0.1.7
  - docrep=0.3.2
  - entrypoints=0.4
  - et_xmlfile=1.1.0
  - executing=0.8.3
  - expat=2.5.0
  - fftw=3.3.10
  - flax=0.6.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=2.001
  - font-ttf-source-code-pro=2.030
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-anaconda=1
  - fonts-conda-ecosystem=1
  - fonttools=4.38.0
  - freetype=2.12.1
  - fribidi=1.0.10
  - frozenlist=1.3.3
  - fsspec=2023.1.0
  - future=0.18.3
  - gcc_impl_linux-64=12.2.0
  - gettext=0.21.1
  - gfortran_impl_linux-64=12.2.0
  - glib=2.76.2
  - glib-tools=2.76.2
  - google-auth=2.16.0
  - google-auth-oauthlib=0.4.6
  - graphite2=1.3.13
  - grpcio=1.51.1
  - gsl=2.7
  - gst-plugins-base=1.21.3
  - gstreamer=1.21.3
  - gstreamer-orc=0.4.33
  - gxx_impl_linux-64=12.2.0
  - h5py=3.7.0
  - harfbuzz=6.0.0
  - hdf5=1.12.2
  - icu=70.1
  - idna=3.3
  - importlib-metadata=6.0.0
  - importlib_metadata=6.0.0
  - intel-openmp=2022.1.0
  - ipykernel=6.9.1
  - ipython=8.4.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.5
  - jack=1.9.21
  - jax=0.4.1
  - jaxlib=0.4.1
  - jedi=0.18.1
  - jinja2=3.0.3
  - joblib=1.2.0
  - jpeg=9e
  - json5=0.9.6
  - jsonschema=4.4.0
  - jupyter=1.0.0
  - jupyter_client=7.2.2
  - jupyter_console=6.4.3
  - jupyter_core=4.10.0
  - jupyter_server=1.18.1
  - jupyterlab=3.4.4
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.12.0
  - jupyterlab_widgets=1.0.0
  - kernel-headers_linux-64=2.6.32
  - keyutils=1.6.1
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lame=3.100
  - lcms2=2.14
  - ld_impl_linux-64=2.39
  - lerc=4.0.0
  - libabseil=20220623.0
  - libaec=1.0.6
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcap=2.66
  - libcblas=3.9.0
  - libclang=15.0.6
  - libclang13=15.0.6
  - libcups=2.3.3
  - libcurl=7.88.1
  - libdb=6.2.32
  - libdeflate=1.14
  - libedit=3.1.20210910
  - libev=4.33
  - libevent=2.1.10
  - libffi=3.4.2
  - libflac=1.4.2
  - libgcc-devel_linux-64=12.2.0
  - libgcc-ng=12.2.0
  - libgcrypt=1.10.1
  - libgfortran-ng=12.2.0
  - libgfortran5=12.2.0
  - libglib=2.76.2
  - libgomp=12.2.0
  - libgpg-error=1.46
  - libgrpc=1.51.1
  - libhwloc=2.8.0
  - libiconv=1.17
  - libjpeg-turbo=2.1.4
  - liblapack=3.9.0
  - libllvm11=11.1.0
  - libllvm15=15.0.6
  - libnghttp2=1.51.0
  - libnsl=2.0.0
  - libogg=1.3.5
  - libopus=1.3.1
  - libpng=1.6.39
  - libpq=15.1
  - libprotobuf=3.21.12
  - libsanitizer=12.2.0
  - libsndfile=1.1.0
  - libsodium=1.0.18
  - libsqlite=3.40.0
  - libssh2=1.10.0
  - libstdcxx-devel_linux-64=12.2.0
  - libstdcxx-ng=12.2.0
  - libsystemd0=252
  - libtiff=4.5.0
  - libtool=2.4.6
  - libudev1=252
  - libuuid=2.32.1
  - libvorbis=1.3.7
  - libwebp-base=1.2.4
  - libxcb=1.13
  - libxkbcommon=1.0.3
  - libxml2=2.10.3
  - libzlib=1.2.13
  - llvmlite=0.39.1
  - lz4-c=1.9.3
  - make=4.3
  - markdown=3.4.1
  - markupsafe=2.1.1
  - matplotlib-base=3.6.2
  - matplotlib-inline=0.1.2
  - mistune=0.8.4
  - mkl=2022.1.0
  - ml-collections=0.1.1
  - mpg123=1.31.1
  - msgpack-python=1.0.4
  - mudata=0.2.1
  - multidict=6.0.4
  - multipledispatch=0.6.0
  - munkres=1.0.7
  - mysql-common=8.0.31
  - mysql-libs=8.0.31
  - natsort=8.2.0
  - nbclassic=0.3.5
  - nbclient=0.5.13
  - nbconvert=6.4.4
  - nbformat=5.3.0
  - nccl=2.14.3.1
  - ncurses=6.3
  - nest-asyncio=1.5.5
  - networkx=3.0
  - notebook=6.4.12
  - nspr=4.35
  - nss=3.82
  - numba=0.56.4
  - numpy=1.23.5
  - numpyro=0.11.0
  - oauthlib=3.2.2
  - openjpeg=2.5.0
  - openpyxl=3.0.10
  - openssl=3.1.0
  - opt_einsum=3.3.0
  - optax=0.1.4
  - packaging=21.3
  - pandas=1.5.2
  - pandocfilters=1.5.0
  - pango=1.50.14
  - parso=0.8.3
  - patsy=0.5.3
  - pcre2=10.40
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.4.0
  - pip=22.3.1
  - pixman=0.40.0
  - ply=3.11
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.20
  - prompt_toolkit=3.0.20
  - protobuf=4.21.12
  - pthread-stubs=0.3
  - ptyprocess=0.7.0
  - pulseaudio=16.1
  - pure_eval=0.2.2
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycparser=2.21
  - pydeprecate=0.3.2
  - pygments=2.11.2
  - pyjwt=2.6.0
  - pynndescent=0.5.8
  - pyopenssl=22.0.0
  - pyparsing=3.0.4
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pyro-api=0.1.2
  - pyro-ppl=1.8.4
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - python=3.9.15
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.15.1
  - python_abi=3.9
  - pytorch=1.12.1
  - pytorch-lightning=1.7.7
  - pytorch-mutex=1.0
  - pytz=2022.1
  - pyu2f=0.1.5
  - pyyaml=6.0
  - pyzmq=23.2.0
  - qt-main=5.15.6
  - qtconsole=5.3.1
  - qtpy=2.0.1
  - r-base=4.2.3
  - re2=2022.06.01
  - readline=8.1.2
  - requests=2.28.1
  - requests-oauthlib=1.3.1
  - rich=11.1.0
  - rpy2=3.5.11
  - rsa=4.9
  - scanpy=1.9.1
  - scikit-learn=1.2.0
  - scipy=1.9.1
  - scvi-tools=0.19.0
  - seaborn=0.12.2
  - seaborn-base=0.12.2
  - sed=4.8
  - send2trash=1.8.0
  - session-info=1.0.0
  - setuptools=65.6.3
  - simplegeneric=0.8.1
  - sip=6.6.2
  - six=1.16.0
  - sniffio=1.2.0
  - soupsieve=2.3.1
  - stack_data=0.2.0
  - statsmodels=0.13.5
  - stdlib-list=0.8.0
  - sysroot_linux-64=2.12
  - tbb=2021.7.0
  - tensorboard=2.11.2
  - tensorboard-data-server=0.6.1
  - tensorboard-plugin-wit=1.8.1
  - terminado=0.13.1
  - testpath=0.6.0
  - threadpoolctl=3.1.0
  - tk=8.6.12
  - tktable=2.10
  - toml=0.10.2
  - toolz=0.12.0
  - torchmetrics=0.11.0
  - tornado=6.1
  - tqdm=4.64.1
  - traitlets=5.1.1
  - typing-extensions=4.4.0
  - typing_extensions=4.4.0
  - tzdata=2022g
  - tzlocal=5.0.1
  - umap-learn=0.5.3
  - unicodedata2=15.0.0
  - urllib3=1.26.11
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=0.58.0
  - werkzeug=2.2.2
  - wheel=0.38.4
  - widgetsnbextension=3.5.2
  - xcb-util=0.4.0
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.0
  - xcb-util-renderutil=0.3.9
  - xcb-util-wm=0.4.1
  - xlrd=1.2.0
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.8.4
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-libxt=1.2.1
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.6
  - yaml=0.2.5
  - yarl=1.8.2
  - zeromq=4.3.4
  - zipp=3.11.0
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
    - igraph==0.10.4
    - leidenalg==0.9.1
    - texttable==1.6.7
